language: php
dist: trusty
php:
- '7.1'
- '7.0'
- '5.6'
- '5.5'
- '5.4'

matrix:
    fast_finish: true
    include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise


install:
- composer install
- if [[ "$TRAVIS_PHP_VERSION" == "5.2" ]]; then composer remove --dev phpunit/phpunit; fi
- phpenv local --unset

script:
- echo $TRAVIS_PHP_VERSION
- if [[ "$TRAVIS_PHP_VERSION" == "5.2" ]]; then phpunit; else ./vendor/bin/phpunit; fi
